### ISSUE TITLE
The certificate chain in the configuration details of the certificate is invalid.

### ISSUE THREAD

**Issue by yhcho87** [therealcmj/certbot-dns-oci#1]
hello,

I'm trying to import the certificate that follows your post. (https://blogs.oracle.com/post/get-certificates-from-lets-encrypt-for-your-oci-services-the-easy-way)
but It failed with this message "The certificate chain in the configuration details of the certificate is invalid."

Please give me your help? Thanks

**Comment by therealcmj** [comment]
Hi. If you run into this issue you probably need to add the CA's root cert.

To make things easy for you I attached it.

[isrgrootx1.txt](https://github.com/therealcmj/certbot-dns-oci/files/9896830/isrgrootx1.txt)

**Comment by therealcmj** [comment]
I believe the solution I provided above solves this. If not please re-open.

**Comment by yhcho87** [comment]
Hi, may I know where should I add the CA's root cert that you attached? Please advise me. Thanks

**Comment by yhcho87** [comment]
Hi

> Hi, may I know where should I add the CA's root cert that you attached? Please advise me. Thanks

Added root CA file after "chain.pem" and successfully registered with OCI Certificate Service. Thank you.
