### ISSUE TITLE
wildcard certificate

### ISSUE THREAD

**Issue by hao-vizseek** [therealcmj/certbot-dns-oci#2]
Hello,

does this plugin support DNS challenge for wildcard SSL certificates?

**Comment by damithkothalawala** [comment]
Hi @hao-vizseek 

Yes it can be used for wildcard dns as well.

but if you use *.sub.example.com then you will get an error like following.

Domain name contains an invalid wildcard. A wildcard is only permitted before the first dot in a domain name
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /opt/logs/letsencrypt.log or re-run Certbot with -v for more details.

**Comment by therealcmj** [comment]
Sorry I didn't see this before. @damithkothalawala provided the correct answer. Please feel free to re-open if you have any other questions.
